### ISSUE TITLE
JS code cannot be loaded

### ISSUE THREAD

**Issue by paulvt** [keeps/redmine_wikicipher#24]
I cannot get the plugin to work with Redmine 2.4.2.  I tried to use the 2.2.x version but that is definitely incompatible.  The 2.5.x version loads fine, but there is no cipher icon in the editor.

The JS console logs:

    Uncaught TypeError: document.observe is not a function @ redmine_wikicipher.js:1

It seems that `document.observe` is a PrototypeJS method, which is not loaded, and Rails uses jQuery?

**Comment by hsilva-keep** [comment]
@paulvt First of all thank you for the feedback. Secondly, as you can understand from the readme we didn't tested this plugin in the version you are currently using and therefore we cannot ensure that it will work flawlessly. As this is an open source project, and as we don't have currently time to investigate the problem you're reporting, the two alternatives we would suggest to you are: 1) upgrade redmine to version 2.5.x ; 2) if that is not possible, you could investigate deeper and if you find the solution you can provide a fix to the plugin for that particular version of redmine (2.4.x)  using a pull request, that we would happily analyze and integrate in the appropriate branch (a new branch would be created for 2.4.x).

Best regards,

Hélder Silva

**Comment by paulvt** [comment]
Dear Hélder,

But the JS code already stems from 2012 as per commit history.  So, I assume that the JS code worked then, and given that I am using the 2.5.x plugin, it no longer works now? Are there any includes I should see before the plugin JS, such as prototype JS?
Not that I'm not willing to look into things, but I find it weird that code unchanged during 4 years doesn't work (anymore).

**Comment by hsilva-keep** [comment]
@paulvt The thing is we are currently using redmine 2.5.2 with the plugin from the branch 2.5.x and it is working 100%. Aside from that, it's kind of hard to tell what's going on as we didn't tested that setup, i.e. redmine 2.4.x with the redmine wikicypher (and any other plugins/setup particularities). My apologies for not being able to help you further but we cannot test every single possible scenario and we only ensure that it works on the tested scenarios (1.4.x, 2.2.x & 2.5.x).

**Comment by paulvt** [comment]
Made a small fix to make it run on 2.4.  Given that it is not supposed to be supported, I'll close this issue.
